# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: InventoryManager CI script

# The workflow is triggered on push events to the "master" branch
# and also on pull requests targeting the "master" branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    - '*'

# environmental variables needed so that GitHub action workflow runner can
# perform the necessary build and testing operations successfully
env:
  MONGODB_URI: "mongodb+srv://m001-student:m001-mongodb-basics@sandbox.zagvop3.mongodb.net/inventoryManager"
  MONGODB_TEST_URL: "mongodb+srv://m001-student:m001-mongodb-basics@inventorymanagertestdb.sisgvlf.mongodb.net/testDB"
  PORT: 5000
  REACT_APP_INVENTORY_MANAGER_BACKEND_URL: "http://localhost:5000"

jobs:
  build:

    # The workflow defines a single job named "build" that runs
    # on the "ubuntu-latest" runner.
    runs-on: ubuntu-latest

    # The job uses the "strategy" section to create a matrix of Node.js
    # versions to test the code across different Node.js releases.
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 18.x, 20.x ]

    steps:
      # uses the actions/checkout action to clone the repository from
      # the "master" branch into the runner.
      - uses: actions/checkout@v3

      # Enable caching for inventoryManager/Client directory
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for inventoryManager/Client
        working-directory: ./Client
        run: npm ci

      - name: Build inventoryManager/Client
        working-directory: ./Client
        run: npm run build --if-present

      - name: Install dependencies for inventoryManager/Server
        working-directory: ./Server
        run: npm ci

      - name: Run unit tests for inventoryManager/Server
        working-directory: ./Server
        run: npm test -- InventoryItems.validate.test.js

      - name: Run integration tests for Categories route handlers
        working-directory: ./Server
        run: npm test -- categories.routes.test.js

      - name: Run integration tests for InventoryItems.GET route handlers
        working-directory: ./Server
        run: npm test -- InventoryItems.GET.routes.test.js

      - name: Run integration tests for InventoryItems.POST route handlers
        working-directory: ./Server
        run: npm test -- InventoryItems.POST.routes.test.js

      - name: Run integration tests for InventoryItems.PUT route handlers
        working-directory: ./Server
        run: npm test -- InventoryItems.PUT.routes.test.js

      - name: Run integration tests for InventoryItems.DELETE route handlers
        working-directory: ./Server
        run: npm test -- InventoryItems.DELETE.routes.test.js
