# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: InventoryManager CI script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies for inventoryManager/Client
        run: npm ci
        working-directory: inventoryManager/Client

      - name: Build inventoryManager/Client
        run: npm run build --if-present
        working-directory: inventoryManager/Client

      - name: Install dependencies for inventoryManager/Server
        run: npm ci
        working-directory: inventoryManager/Server

      - name: Run unit/integration tests for inventoryManager/Server
        run: |
          npm test InventoryItems.validate.test.js
          npm test categories.routes.test.js
          npm test InventoryItems.GET.routes.test.js
          npm test InventoryItems.POST.routes.test.js
          npm test InventoryItems.PUT.routes.test.js
          npm test InventoryItems.DELETE.routes.test.js
        working-directory: inventoryManager/Server
